Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,14 +20,17 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            cd "/home/ubuntu/Taxi Booking"
+            cd /home/ubuntu/Taxi-Booking
+            if [ ! -d ".git" ]; then
+              echo "Error: Not inside a Git repository!"
+              exit 1
+            fi
             git pull origin main
             source venv/bin/activate  # Activate virtual environment
             pip install -r requirements.txt  # Install dependencies
             python manage.py migrate  # Apply database migrations
             python manage.py collectstatic --noinput  # Collect static files
             sudo systemctl restart gunicorn  # Restart backend service
-            sudo systemctl restart nginx  # Restart web server
       - name: Deploy Frontend to S3
         uses: jakejarvis/s3-sync-action@master
         with:
